name: Automatically merge dependabot PR's
on:
  pull_request_target:
    branches: [ master ]
jobs:
    auto-merge:
      name: 🤖 Auto merge dependabot PR
      timeout-minutes: 10
      if: ${{ github.actor == 'dependabot[bot]' }}
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: write
      steps:
        - name: 🤖 Approve PR
          run: gh pr review --approve "$PR_URL"
          env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        - name: 🤖 Enable auto-merge
          run: gh pr merge --auto --rebase "$PR_URL"
          env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}