name: Automatically merge depandabot PR's
on:
  pull_request:
    branches: [ master ]

jobs: 
    auto-merge:
      name: 🤖 Auto merge dependabot PR
      timeout-minutes: 10
      if: ${{ github.actor == 'dependabot[bot]' }}
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: write
      steps:
        - name: 🤖 Merge PR from dependabot
          uses: fastify/github-action-merge-dependabot@latest
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            target: minor
            merge-method: rebase
